sonar.projectKey=rgkim-hsu_Plant-Disease-Monitoring
sonar.organization=rgkim-hsu
sonar.projectName=Plant Disease Monitoring (Flask + React)
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/dist/**,**/build/**,**/*.ipynb,**/static/**
sonar.python.version=3.8,3.9,3.10
